-- V1 — Schéma initial, aligné sur docs/diagrammes/D2-modele-donnees.md
-- SQL portable PostgreSQL / H2 (mode PostgreSQL) : GENERATED BY DEFAULT AS IDENTITY.
-- Toute évolution du schéma se fera dans une nouvelle migration V2__, V3__… (contrainte B5).

CREATE TABLE promotion (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(120) NOT NULL
);

CREATE TABLE etudiant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(120) NOT NULL,
    promotion_id  BIGINT NOT NULL REFERENCES promotion (id)
);

CREATE TABLE session (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre          VARCHAR(200) NOT NULL,
    promotion_id   BIGINT NOT NULL REFERENCES promotion (id),
    code           VARCHAR(6)   NOT NULL,
    ouverture_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    cloture_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE presence (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session (id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant (id),
    source       VARCHAR(10) NOT NULL,
    cree_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id)  -- RG16
);

CREATE TABLE exercice (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session (id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant (id),
    lien         VARCHAR(2048) NOT NULL,
    statut       VARCHAR(12) NOT NULL,
    depose_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id)  -- RG17
);

-- Une seule relecture par exercice (RG6) : unicité sur exercice_id.
-- note / commentaire / rendue_at sont NULL tant que le relecteur n'a pas rendu (EF4 → EF5).
CREATE TABLE relecture (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id   BIGINT NOT NULL REFERENCES exercice (id),
    relecteur_id  BIGINT NOT NULL REFERENCES etudiant (id),
    note          INTEGER,
    commentaire   VARCHAR(2000),
    rendue_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id)
);

-- Trace des codes erronés : alimente le blocage de 2 minutes après 5 échecs
-- (Q4, RG3) — exigence Could (EF12), schéma posé dès V1 pour éviter une migration de plus.
CREATE TABLE tentative_code (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL REFERENCES session (id),
    etudiant_id  BIGINT NOT NULL REFERENCES etudiant (id),
    echec_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_session_code          ON session (code);
CREATE INDEX idx_presence_session      ON presence (session_id);
CREATE INDEX idx_exercice_session      ON exercice (session_id);
CREATE INDEX idx_relecture_relecteur   ON relecture (relecteur_id);
